// Mocks generated by Mockito 5.3.2 from annotations
// in poke_dart/test/pokemon_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:poke_dart/model/fetch_pokemon_response.dart' as _i2;
import 'package:poke_dart/service/pokemon_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchPokemonResponse_0 extends _i1.SmartFake
    implements _i2.FetchPokemonResponse {
  _FakeFetchPokemonResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PokemonService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonService extends _i1.Mock implements _i3.PokemonService {
  MockPokemonService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FetchPokemonResponse> fetchPokemon({_i5.Options? options}) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchPokemon,
          [],
          {#options: options},
        ),
        returnValue: _i4.Future<_i2.FetchPokemonResponse>.value(
            _FakeFetchPokemonResponse_0(
          this,
          Invocation.method(
            #fetchPokemon,
            [],
            {#options: options},
          ),
        )),
      ) as _i4.Future<_i2.FetchPokemonResponse>);
}
