name: poke_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  dio: ^4.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  retrofit_generator: ^4.2.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  mockito: ^5.3.2
  equatable: ^2.0.5
